name: "Build docs"
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_call:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -b html docsrc/ _build -f /tmp/sphinx.log "
        docs-folder: "docs/"
        


    - name: Archive UserReleaseNotes 
      uses: actions/upload-artifact@v3
      with:
        name: Docs_Output
        path: |
          docs/build/html


    
