name: "Build docs"
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_call:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install the package your documenting together with its dependencies.
      run: |
        pip install .
    - name: Build the sphinx documentation and posts warnings as github comments.
      uses: rickstaa/sphinx-action@master
      with:
        docs-folder: "./docs"
        


    - name: Archive UserReleaseNotes 
      uses: actions/upload-artifact@v3
      with:
        name: Docs_Output
        path: |
          docs/build/html


    
