name: "Build docs"
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_call:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Installing sphinx packages
      run: pip install -r requirements.txt

    - name: Install dependencies
      run: pip install -r docs/requirements.txt


    - name: Build docs
      run: cd docs && make html
        


    - name: Archive UserReleaseNotes 
      uses: actions/upload-artifact@v3
      with:
        name: Docs_Output
        path: |
          docs/build/html


    
