name: "Build docs"
on:
  push:
    tags:
    - '*'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'


    - name: Insert firmware version
      run: echo "__version__" "=" '"'$GITHUB_REF_NAME'"' >> lumache.py

    - name: Installing sphinx packages
      run: pip install -r requirements.txt

    - name: Install dependencies for docs
      run: pip install -r docs/requirements.txt

    - name: Install enviroment
      run: pip install -e .

    - name: Install pdf generator
      run: sudo apt-get update && sudo apt-get install texmaker gummi texlive texlive-full texlive-latex-recommended latexdraw intltool-debian lacheck lmodern luatex po-debconf tex-common texlive-binaries texlive-extra-utils texlive-latex-base texlive-latex-base-doc texlive-luatex texlive-xetex texlive-lang-cyrillic texlive-fonts-extra texlive-science texlive-latex-extra texlive-pstricks -y
      
    - name: Build docs
      run: make --directory docs html
        
    - name: Build pdf
      run: make --directory docs latexpdf

    - name: Save build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Docs_Output
        path: |
          docs/build


    - name: Move html files
      run: mv docs/build/html lumache_html

    - name: ZIP files
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        path: 'lumache_html' 



    - name: Upload html to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release.zip
        asset_name: Lumache_HtmlDoc_$tag.zip
        tag: ${{ github.ref }}


    - name: Upload pdf to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: docs/build/latex/lumache.pdf
        asset_name: Lumache_Doc_$tag.pdf
        tag: ${{ github.ref }}


    
